export interface Listing {
  id: number
  mls_id: number
  mls_update_date: string
  status: string
  price: number
  sqft: number
  tax?: number
  homeOwnerFee?: number
  photos?: string
  photosThumb?: string
  bdrooms: number
  bthrooms: number
  county?: string
  city: string
  area: string
  address?: string
  direction?: string
  subdivision?: string
  owner?: string
  phone?: string
  lotDim?: string
  Bdroom1?: string
  Bdroom2?: string
  Bdroom3?: string
  Bdroom4?: string
  Bdroom5?: string
  diningDim?: string
  livingDim?: string
  kitchenDim?: string
  familyDim?: string
  yearBuilt?: string
  pool?: boolean
  waterfront?: boolean
  fireplace?: boolean
  warranty?: boolean
  internet?: boolean
  remarks?: string
  createdAt?: string
  updatedAt?: string
}